[package]
name = "transaction_decoder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.26.0"
hex = "0.4.2"

[dev-dependencies]
assert_cmd = "1.0.4"
predicates = "1.0.3"